class BatchDataModel {
  String? code,
      name,
      farmerCode,
      farmerName,
      qty,
      fromDate,
      endingDate,
      employee,
      scc,
      sfc,
      acc,
      afc,
      cons;
  BatchDataModel({
    this.code,
    this.name,
    this.farmerCode,
    this.farmerName,
    this.qty,
    this.fromDate,
    this.endingDate,
    this.employee,
    this.scc,
    this.sfc,
    this.acc,
    this.afc,
    this.cons
  });
}
